/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iGovernorInnImplSol from "./IGovernorINNImpl.sol";
export { IGovernorINN__factory } from "./IGovernorINN__factory";
