/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export { IGovernorINNImplV2__factory } from "./IGovernorINNImplV2__factory";
