/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace IGovernorINN {
  export type ProposalRequestStruct = {
    offchainID: BytesLike;
    proposalType: BigNumberish;
    actionType: BigNumberish;
    description: string;
    data: BytesLike;
  };

  export type ProposalRequestStructOutput = [
    string,
    number,
    number,
    string,
    string
  ] & {
    offchainID: string;
    proposalType: number;
    actionType: number;
    description: string;
    data: string;
  };
}

export interface IGovernorINNInterface extends utils.Interface {
  functions: {
    "cancel(bytes32,string)": FunctionFragment;
    "castVote(string,bytes32,uint8)": FunctionFragment;
    "execute(bytes32)": FunctionFragment;
    "hasVoted(bytes32,address)": FunctionFragment;
    "hashProposal(bytes32,bytes32,address,uint8,uint8,bytes)": FunctionFragment;
    "name()": FunctionFragment;
    "propose((bytes32,uint8,uint8,string,bytes),bytes)": FunctionFragment;
    "state(bytes32)": FunctionFragment;
    "version()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "cancel"
      | "castVote"
      | "execute"
      | "hasVoted"
      | "hashProposal"
      | "name"
      | "propose"
      | "state"
      | "version"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cancel",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castVote",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "execute", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hashProposal",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "propose",
    values: [IGovernorINN.ProposalRequestStruct, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "state", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "propose", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "ExitInvestmentProposalCreated(bytes32,address,address,uint256,bytes32,bytes32,string,uint16)": EventFragment;
    "FreezeInvestmentProposalCreated(bytes32,address,address,bytes32,bytes32)": EventFragment;
    "NewInvestmentProposalCreated(bytes32,address,address,uint256,bytes32,bytes32,string,uint16)": EventFragment;
    "NewValidatorProposalCreated(bytes32,address,address,bytes32,bytes32,string)": EventFragment;
    "ProposalCanceled(bytes32,string)": EventFragment;
    "ProposalExecuted(bytes32)": EventFragment;
    "UnfreezeInvestmentProposalCreated(bytes32,address,address,bytes32,bytes32)": EventFragment;
    "VoteCast(address,bytes32,uint8,string)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "ExitInvestmentProposalCreated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "FreezeInvestmentProposalCreated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewInvestmentProposalCreated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewValidatorProposalCreated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ProposalExecuted"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "UnfreezeInvestmentProposalCreated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "VoteCast"): EventFragment;
}

export interface ExitInvestmentProposalCreatedEventObject {
  proposalId: string;
  proposer: string;
  validatorEOA: string;
  tokenOffer: BigNumber;
  offchainID: string;
  description: string;
  startupName: string;
  sharedStake: number;
}
export type ExitInvestmentProposalCreatedEvent = TypedEvent<
  [string, string, string, BigNumber, string, string, string, number],
  ExitInvestmentProposalCreatedEventObject
>;

export type ExitInvestmentProposalCreatedEventFilter =
  TypedEventFilter<ExitInvestmentProposalCreatedEvent>;

export interface FreezeInvestmentProposalCreatedEventObject {
  proposalId: string;
  proposer: string;
  account: string;
  offchainID: string;
  description: string;
}
export type FreezeInvestmentProposalCreatedEvent = TypedEvent<
  [string, string, string, string, string],
  FreezeInvestmentProposalCreatedEventObject
>;

export type FreezeInvestmentProposalCreatedEventFilter =
  TypedEventFilter<FreezeInvestmentProposalCreatedEvent>;

export interface NewInvestmentProposalCreatedEventObject {
  proposalID: string;
  proposer: string;
  startupEOA: string;
  tokenOffer: BigNumber;
  offchainID: string;
  description: string;
  startupName: string;
  sharedStake: number;
}
export type NewInvestmentProposalCreatedEvent = TypedEvent<
  [string, string, string, BigNumber, string, string, string, number],
  NewInvestmentProposalCreatedEventObject
>;

export type NewInvestmentProposalCreatedEventFilter =
  TypedEventFilter<NewInvestmentProposalCreatedEvent>;

export interface NewValidatorProposalCreatedEventObject {
  proposalID: string;
  proposer: string;
  validatorEOA: string;
  offchainID: string;
  description: string;
  validatorName: string;
}
export type NewValidatorProposalCreatedEvent = TypedEvent<
  [string, string, string, string, string, string],
  NewValidatorProposalCreatedEventObject
>;

export type NewValidatorProposalCreatedEventFilter =
  TypedEventFilter<NewValidatorProposalCreatedEvent>;

export interface ProposalCanceledEventObject {
  proposalId: string;
  reason: string;
}
export type ProposalCanceledEvent = TypedEvent<
  [string, string],
  ProposalCanceledEventObject
>;

export type ProposalCanceledEventFilter =
  TypedEventFilter<ProposalCanceledEvent>;

export interface ProposalExecutedEventObject {
  proposalId: string;
}
export type ProposalExecutedEvent = TypedEvent<
  [string],
  ProposalExecutedEventObject
>;

export type ProposalExecutedEventFilter =
  TypedEventFilter<ProposalExecutedEvent>;

export interface UnfreezeInvestmentProposalCreatedEventObject {
  proposalID: string;
  proposer: string;
  account: string;
  offchainID: string;
  description: string;
}
export type UnfreezeInvestmentProposalCreatedEvent = TypedEvent<
  [string, string, string, string, string],
  UnfreezeInvestmentProposalCreatedEventObject
>;

export type UnfreezeInvestmentProposalCreatedEventFilter =
  TypedEventFilter<UnfreezeInvestmentProposalCreatedEvent>;

export interface VoteCastEventObject {
  voter: string;
  proposalId: string;
  vote: number;
  reason: string;
}
export type VoteCastEvent = TypedEvent<
  [string, string, number, string],
  VoteCastEventObject
>;

export type VoteCastEventFilter = TypedEventFilter<VoteCastEvent>;

export interface IGovernorINN extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IGovernorINNInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cancel(
      proposalId: BytesLike,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    castVote(
      reason: string,
      proposalId: BytesLike,
      vote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    execute(
      proposalId: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasVoted(
      proposalId: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    hashProposal(
      offchainID: BytesLike,
      descriptionHash: BytesLike,
      proposer: string,
      proposalType: BigNumberish,
      actionType: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    name(overrides?: CallOverrides): Promise<[string]>;

    propose(
      proposalRequest: IGovernorINN.ProposalRequestStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    state(proposalId: BytesLike, overrides?: CallOverrides): Promise<[number]>;

    version(overrides?: CallOverrides): Promise<[string]>;
  };

  cancel(
    proposalId: BytesLike,
    reason: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  castVote(
    reason: string,
    proposalId: BytesLike,
    vote: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  execute(
    proposalId: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasVoted(
    proposalId: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  hashProposal(
    offchainID: BytesLike,
    descriptionHash: BytesLike,
    proposer: string,
    proposalType: BigNumberish,
    actionType: BigNumberish,
    data: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  name(overrides?: CallOverrides): Promise<string>;

  propose(
    proposalRequest: IGovernorINN.ProposalRequestStruct,
    signature: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  state(proposalId: BytesLike, overrides?: CallOverrides): Promise<number>;

  version(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    cancel(
      proposalId: BytesLike,
      reason: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    castVote(
      reason: string,
      proposalId: BytesLike,
      vote: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    execute(proposalId: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    hasVoted(
      proposalId: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    hashProposal(
      offchainID: BytesLike,
      descriptionHash: BytesLike,
      proposer: string,
      proposalType: BigNumberish,
      actionType: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    name(overrides?: CallOverrides): Promise<string>;

    propose(
      proposalRequest: IGovernorINN.ProposalRequestStruct,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    state(proposalId: BytesLike, overrides?: CallOverrides): Promise<number>;

    version(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "ExitInvestmentProposalCreated(bytes32,address,address,uint256,bytes32,bytes32,string,uint16)"(
      proposalId?: BytesLike | null,
      proposer?: string | null,
      validatorEOA?: string | null,
      tokenOffer?: null,
      offchainID?: null,
      description?: null,
      startupName?: null,
      sharedStake?: null
    ): ExitInvestmentProposalCreatedEventFilter;
    ExitInvestmentProposalCreated(
      proposalId?: BytesLike | null,
      proposer?: string | null,
      validatorEOA?: string | null,
      tokenOffer?: null,
      offchainID?: null,
      description?: null,
      startupName?: null,
      sharedStake?: null
    ): ExitInvestmentProposalCreatedEventFilter;

    "FreezeInvestmentProposalCreated(bytes32,address,address,bytes32,bytes32)"(
      proposalId?: BytesLike | null,
      proposer?: string | null,
      account?: string | null,
      offchainID?: null,
      description?: null
    ): FreezeInvestmentProposalCreatedEventFilter;
    FreezeInvestmentProposalCreated(
      proposalId?: BytesLike | null,
      proposer?: string | null,
      account?: string | null,
      offchainID?: null,
      description?: null
    ): FreezeInvestmentProposalCreatedEventFilter;

    "NewInvestmentProposalCreated(bytes32,address,address,uint256,bytes32,bytes32,string,uint16)"(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      startupEOA?: string | null,
      tokenOffer?: null,
      offchainID?: null,
      description?: null,
      startupName?: null,
      sharedStake?: null
    ): NewInvestmentProposalCreatedEventFilter;
    NewInvestmentProposalCreated(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      startupEOA?: string | null,
      tokenOffer?: null,
      offchainID?: null,
      description?: null,
      startupName?: null,
      sharedStake?: null
    ): NewInvestmentProposalCreatedEventFilter;

    "NewValidatorProposalCreated(bytes32,address,address,bytes32,bytes32,string)"(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      validatorEOA?: string | null,
      offchainID?: null,
      description?: null,
      validatorName?: null
    ): NewValidatorProposalCreatedEventFilter;
    NewValidatorProposalCreated(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      validatorEOA?: string | null,
      offchainID?: null,
      description?: null,
      validatorName?: null
    ): NewValidatorProposalCreatedEventFilter;

    "ProposalCanceled(bytes32,string)"(
      proposalId?: BytesLike | null,
      reason?: null
    ): ProposalCanceledEventFilter;
    ProposalCanceled(
      proposalId?: BytesLike | null,
      reason?: null
    ): ProposalCanceledEventFilter;

    "ProposalExecuted(bytes32)"(
      proposalId?: BytesLike | null
    ): ProposalExecutedEventFilter;
    ProposalExecuted(
      proposalId?: BytesLike | null
    ): ProposalExecutedEventFilter;

    "UnfreezeInvestmentProposalCreated(bytes32,address,address,bytes32,bytes32)"(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      account?: string | null,
      offchainID?: null,
      description?: null
    ): UnfreezeInvestmentProposalCreatedEventFilter;
    UnfreezeInvestmentProposalCreated(
      proposalID?: BytesLike | null,
      proposer?: string | null,
      account?: string | null,
      offchainID?: null,
      description?: null
    ): UnfreezeInvestmentProposalCreatedEventFilter;

    "VoteCast(address,bytes32,uint8,string)"(
      voter?: string | null,
      proposalId?: BytesLike | null,
      vote?: null,
      reason?: null
    ): VoteCastEventFilter;
    VoteCast(
      voter?: string | null,
      proposalId?: BytesLike | null,
      vote?: null,
      reason?: null
    ): VoteCastEventFilter;
  };

  estimateGas: {
    cancel(
      proposalId: BytesLike,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    castVote(
      reason: string,
      proposalId: BytesLike,
      vote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    execute(
      proposalId: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasVoted(
      proposalId: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    hashProposal(
      offchainID: BytesLike,
      descriptionHash: BytesLike,
      proposer: string,
      proposalType: BigNumberish,
      actionType: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    propose(
      proposalRequest: IGovernorINN.ProposalRequestStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    state(proposalId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    cancel(
      proposalId: BytesLike,
      reason: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    castVote(
      reason: string,
      proposalId: BytesLike,
      vote: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      proposalId: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasVoted(
      proposalId: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashProposal(
      offchainID: BytesLike,
      descriptionHash: BytesLike,
      proposer: string,
      proposalType: BigNumberish,
      actionType: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    propose(
      proposalRequest: IGovernorINN.ProposalRequestStruct,
      signature: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    state(
      proposalId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
